### ISSUE TITLE
Possible encoding problem in mix.exs file

### ISSUE THREAD

**Issue by riverrun** [devinus/markdown#12]
In the mix.exs file, on lines 7 and 10, there are calls to Mix.Shell.info. These calls might cause errors with certain locales / charsets. It might be an idea to change `Mix.Shell.info` to `IO.binwrite`.
Further information: I had this problem with an application I'm developing, where a user using a Chinese charset was getting errors when this function was calling `:io.put_chars`. Using `IO.binwrite` solved the issue.

**Comment by josevalim** [comment]
Thank you!
